---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: express-demo
  namespace: express-demo
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: express-demo
  chart:
    repository: https://h.cfcr.io/bjornmagnusson/default
    name: express-demo
    version: v0.2.0
  values:
    image:
      repository: bjornmagnusson/express-demo
      tag: 808f61b6abeb3d2a343a583d880142c09c4f67e8
    ingress:
      enabled: true
