---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: express-demo
  namespace: express-demo
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: express-demo
  chart:
    repository: https://h.cfcr.io/bjornmagnusson/default
    name: express-demo
    version: v0.2.0
  values:
    image:
      repository: bjornmagnusson/express-demo
      tag: b4b81efc74cf0dc55d4222dc35af14876b806195
    ingress:
      enabled: true
