---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: express-demo
  namespace: express-demo
spec:
  chart:
    spec:
      chart: express-demo
      version: v0.3.0
      sourceRef:
        kind: HelmRepository
        name: codefresh
        namespace: flux-system
  values:
    image:
      repository: bjornmagnusson/express-demo
      tag: 988db93b82259e1cd4756bace4e0c9845b25f85d
    ingress:
      enabled: false 
  interval: 1m0s
