---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: regionalmap
  namespace: flux-system
spec:
  chart:
    spec:
      chart: regionalmap
      sourceRef:
        name: "codefresh"
      values:
        image:
          repository: bjornmagnusson/regionalmap
          tag: 8b290932fd2d94ace8ff13004fea7fd8265d57c7  
  interval: 1m0s