---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flux
  namespace: flux
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: flux
  chart:
    repository: https://charts.fluxcd.io
    name: flux
    version: 1.2.0
  values:
    helmOperator:
      create: false
    git:
      url: "git@github.com:bjornmagnusson/flux-config.git"
      branch: master
    image:
      repository: raspbernetes/flux
      tag: fb3a8dbf86748c0a987bf7657cb59e840c6c651d
    syncGarbageCollection:
      enabled: true
      dry: false
    registry:
      disableScanning: false
    prometheus:
      enabled: false
