---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: flux
  namespace: flux
spec:
  releaseName: flux
  chart:
    repository: https://charts.fluxcd.io
    name: flux
    version: 1.3.0
  values:
    git:
      url: "git@github.com:bjornmagnusson/flux-config.git"
      branch: arm
    image:
      repository: raspbernetes/flux
    syncGarbageCollection:
      enabled: true
    prometheus:
      enabled: false
