---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: regionalmap
  namespace: regionalmap
  annotations:
    fluxcd.io/automated: "true"
spec:
  releaseName: regionalmap
  chart:
    repository: https://h.cfcr.io/bjornmagnusson/default
    name: regionalmap
    version: 0.1.0
  values:
    image:
      repository: bjornmagnusson/regionalmap
      tag: 5899935db6d5c07d3a1da02eda9c1c15438f3729
